language: node_js
sudo: required
services:
  - docker

node_js:
  - "6"
  - "6.1"
  - "5.11"

before_install:
  - npm install -g node-gyp
before_script:
  - npm install
  - npm install -g standard
  - npm install -g mocha
  - docker-compose build
  - docker-compose up -d
  - sleep 3
script:
  - npm test
after_script:
  - docker-compose kill
