language: node_js
sudo: required
services:
  - docker
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "7"
script:
  - docker-compose rm -f
  - docker-compose build
  - docker-compose -f docker-compose.test.yml up --timeout 1 --no-build -d
  - docker-compose stop
after_script:
  - docker-compose kill
after_success: 'npm run coveralls'
